# Generated by Django 4.2.1 on 2023-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosCatProyecto',
            fields=[
                ('id_proyecto_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('ruta', models.CharField(max_length=150)),
                ('estatus', models.IntegerField()),
            ],
            options={
                'db_table': 'proyecto_cat_proyecto',
                'managed': True,
            },
        ),
    ]
