# Generated by Django 4.2.1 on 2023-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proyectoscatproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoscatproyecto',
            name='dueño',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
