# Generated by Django 4.2.1 on 2023-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proyectoscatproyecto_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoscatproyecto',
            name='img',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='proyectoscatproyecto',
            name='ruta',
            field=models.CharField(default='', max_length=150),
        ),
    ]
